// <auto-generated />
using Labb2_Avancerad.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb2AvanceradV2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221002195106_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-rc.1.22426.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Labb2_Avancerad.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            DepartmentName = "Jewelery, Clothing & Baby"
                        },
                        new
                        {
                            DepartmentId = 2,
                            DepartmentName = "Sports"
                        },
                        new
                        {
                            DepartmentId = 3,
                            DepartmentName = "Toys"
                        },
                        new
                        {
                            DepartmentId = 4,
                            DepartmentName = "Tools"
                        },
                        new
                        {
                            DepartmentId = 5,
                            DepartmentName = "Computers & Grocery"
                        });
                });

            modelBuilder.Entity("Labb2_Avancerad.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Adress = "757 Karley Springs, Gutmannhaven, Saint Helena",
                            DepartmentId = 1,
                            Email = "Bryon_Dach8@gmail.com",
                            FirstName = "Justyn",
                            Gender = "Male",
                            LastName = "Monahan",
                            PhoneNumber = "1-488-481-9394",
                            Salary = 7709.2700000000004
                        },
                        new
                        {
                            EmployeeId = 2,
                            Adress = "40134 Shany Manors, Joanyshire, Germany",
                            DepartmentId = 5,
                            Email = "Hollie85@hotmail.com",
                            FirstName = "Loyce",
                            Gender = "Female",
                            LastName = "Hamill",
                            PhoneNumber = "739.370.1919",
                            Salary = 3333.0500000000002
                        },
                        new
                        {
                            EmployeeId = 3,
                            Adress = "361 Verner Villages, Metzhaven, Cote d'Ivoire",
                            DepartmentId = 3,
                            Email = "Asia.Hettinger@hotmail.com",
                            FirstName = "Timmothy",
                            Gender = "Male",
                            LastName = "Bergstrom",
                            PhoneNumber = "205-718-8790 x089",
                            Salary = 3916.8499999999999
                        },
                        new
                        {
                            EmployeeId = 4,
                            Adress = "293 Wyman Glens, Port Unique, Lebanon",
                            DepartmentId = 5,
                            Email = "Virgil_Torphy40@yahoo.com",
                            FirstName = "Javier",
                            Gender = "Male",
                            LastName = "Jones",
                            PhoneNumber = "1-202-536-0999 x26574",
                            Salary = 9365.3799999999992
                        },
                        new
                        {
                            EmployeeId = 5,
                            Adress = "20583 Abner Port, South Warren, Macedonia",
                            DepartmentId = 1,
                            Email = "Kristofer.Brekke@gmail.com",
                            FirstName = "Jamil",
                            Gender = "Male",
                            LastName = "Leannon",
                            PhoneNumber = "1-902-739-6221 x215",
                            Salary = 9874.3799999999992
                        },
                        new
                        {
                            EmployeeId = 6,
                            Adress = "4897 Christina Well, Hesselburgh, Monaco",
                            DepartmentId = 4,
                            Email = "Bulah39@gmail.com",
                            FirstName = "Aniya",
                            Gender = "Female",
                            LastName = "Dickens",
                            PhoneNumber = "(718) 750-6800",
                            Salary = 5686.2299999999996
                        },
                        new
                        {
                            EmployeeId = 7,
                            Adress = "44571 Kovacek Mountain, New Vena, Pakistan",
                            DepartmentId = 2,
                            Email = "Ruben_Beahan12@yahoo.com",
                            FirstName = "Rebekah",
                            Gender = "Male",
                            LastName = "Kulas",
                            PhoneNumber = "743-571-8792 x52356",
                            Salary = 9442.5499999999993
                        },
                        new
                        {
                            EmployeeId = 8,
                            Adress = "01806 Rippin Forges, Emmerichfort, Ukraine",
                            DepartmentId = 2,
                            Email = "Branson93@hotmail.com",
                            FirstName = "Claud",
                            Gender = "Female",
                            LastName = "Rolfson",
                            PhoneNumber = "(357) 426-1157 x4329",
                            Salary = 8128.0200000000004
                        },
                        new
                        {
                            EmployeeId = 9,
                            Adress = "852 Nels Skyway, O'Reillymouth, Zambia",
                            DepartmentId = 2,
                            Email = "Haleigh.Zboncak@hotmail.com",
                            FirstName = "Lilly",
                            Gender = "Male",
                            LastName = "Mayert",
                            PhoneNumber = "1-287-836-2209 x8720",
                            Salary = 7352.1400000000003
                        },
                        new
                        {
                            EmployeeId = 10,
                            Adress = "610 Melody Vista, Jodyfort, South Georgia and the South Sandwich Islands",
                            DepartmentId = 3,
                            Email = "Lora51@gmail.com",
                            FirstName = "Marcos",
                            Gender = "Female",
                            LastName = "Windler",
                            PhoneNumber = "(953) 486-2780",
                            Salary = 3069.04
                        },
                        new
                        {
                            EmployeeId = 11,
                            Adress = "26801 Frami Forks, Aiyanaton, Papua New Guinea",
                            DepartmentId = 1,
                            Email = "Rhianna45@hotmail.com",
                            FirstName = "Dulce",
                            Gender = "Female",
                            LastName = "Lowe",
                            PhoneNumber = "453.545.4683 x26433",
                            Salary = 6773.9200000000001
                        },
                        new
                        {
                            EmployeeId = 12,
                            Adress = "2550 Bayer Ramp, North Kelton, Ukraine",
                            DepartmentId = 2,
                            Email = "Lamar_Aufderhar@yahoo.com",
                            FirstName = "Johanna",
                            Gender = "Female",
                            LastName = "Cole",
                            PhoneNumber = "1-995-468-0256",
                            Salary = 4572.1199999999999
                        },
                        new
                        {
                            EmployeeId = 13,
                            Adress = "7824 Lafayette Park, Oberbrunnerview, Virgin Islands, British",
                            DepartmentId = 2,
                            Email = "Brandy.Sporer@yahoo.com",
                            FirstName = "Lee",
                            Gender = "Male",
                            LastName = "Conroy",
                            PhoneNumber = "(536) 421-0579 x3740",
                            Salary = 9442.2900000000009
                        },
                        new
                        {
                            EmployeeId = 14,
                            Adress = "456 West Bypass, South Jaime, Cocos (Keeling) Islands",
                            DepartmentId = 3,
                            Email = "Jaylin.Rodriguez@gmail.com",
                            FirstName = "Cassandre",
                            Gender = "Male",
                            LastName = "King",
                            PhoneNumber = "(239) 637-7156 x44743",
                            Salary = 8753.9899999999998
                        },
                        new
                        {
                            EmployeeId = 15,
                            Adress = "676 Marks Meadow, South Malachi, Bouvet Island (Bouvetoya)",
                            DepartmentId = 3,
                            Email = "Dallas.Labadie@gmail.com",
                            FirstName = "Daphney",
                            Gender = "Female",
                            LastName = "O'Hara",
                            PhoneNumber = "1-375-714-4701 x3845",
                            Salary = 6880.3599999999997
                        },
                        new
                        {
                            EmployeeId = 16,
                            Adress = "8839 Koch Mountain, South Calebchester, Somalia",
                            DepartmentId = 1,
                            Email = "Crawford.Koch@yahoo.com",
                            FirstName = "Bartholome",
                            Gender = "Male",
                            LastName = "Breitenberg",
                            PhoneNumber = "(314) 648-6243 x41451",
                            Salary = 6056.9899999999998
                        },
                        new
                        {
                            EmployeeId = 17,
                            Adress = "21857 Hane Manors, Fayfurt, Holy See (Vatican City State)",
                            DepartmentId = 1,
                            Email = "Alanis_Bergstrom@hotmail.com",
                            FirstName = "Christelle",
                            Gender = "Female",
                            LastName = "Wilkinson",
                            PhoneNumber = "(398) 830-1723 x6790",
                            Salary = 1588.4200000000001
                        },
                        new
                        {
                            EmployeeId = 18,
                            Adress = "60704 Orn Knolls, Macejkovicport, Antarctica (the territory South of 60 deg S)",
                            DepartmentId = 5,
                            Email = "Laurianne_Funk2@yahoo.com",
                            FirstName = "Dorothea",
                            Gender = "Female",
                            LastName = "Gusikowski",
                            PhoneNumber = "1-664-885-9052 x70420",
                            Salary = 1198.5
                        },
                        new
                        {
                            EmployeeId = 19,
                            Adress = "1993 Williamson Stream, North Marysefurt, Puerto Rico",
                            DepartmentId = 5,
                            Email = "Carmella67@gmail.com",
                            FirstName = "Okey",
                            Gender = "Female",
                            LastName = "Nolan",
                            PhoneNumber = "621.935.6362 x4168",
                            Salary = 3538.9200000000001
                        },
                        new
                        {
                            EmployeeId = 20,
                            Adress = "19090 Kris Spurs, South Adela, Gambia",
                            DepartmentId = 4,
                            Email = "Stone_Bosco@hotmail.com",
                            FirstName = "Elmira",
                            Gender = "Female",
                            LastName = "Bradtke",
                            PhoneNumber = "630.701.5363 x44744",
                            Salary = 7198.5900000000001
                        });
                });

            modelBuilder.Entity("Labb2_Avancerad.Models.Employee", b =>
                {
                    b.HasOne("Labb2_Avancerad.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });
#pragma warning restore 612, 618
        }
    }
}
