// <auto-generated />
using Labb2_Avancerad.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb2AvanceradV2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220927094221_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-rc.1.22426.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Labb2_Avancerad.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            DepartmentName = "Garden & Movies"
                        },
                        new
                        {
                            DepartmentId = 2,
                            DepartmentName = "Games & Books"
                        },
                        new
                        {
                            DepartmentId = 3,
                            DepartmentName = "Movies & Baby"
                        },
                        new
                        {
                            DepartmentId = 4,
                            DepartmentName = "Electronics & Health"
                        },
                        new
                        {
                            DepartmentId = 5,
                            DepartmentName = "Toys & Kids"
                        });
                });

            modelBuilder.Entity("Labb2_Avancerad.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Adress = "2802 Bechtelar Course, New Zelma, Micronesia",
                            DepartmentId = 4,
                            Email = "Joshuah_Braun71@yahoo.com",
                            FirstName = "Brayan",
                            Gender = "Male",
                            LastName = "Wilkinson",
                            PhoneNumber = "(854) 219-3849 x523",
                            Salary = 4056.1700000000001
                        },
                        new
                        {
                            EmployeeId = 2,
                            Adress = "3609 Strosin Causeway, Darleneburgh, Haiti",
                            DepartmentId = 4,
                            Email = "Alek_Gorczany@hotmail.com",
                            FirstName = "Kathryn",
                            Gender = "Male",
                            LastName = "Nicolas",
                            PhoneNumber = "(723) 735-4526 x8221",
                            Salary = 2788.9099999999999
                        },
                        new
                        {
                            EmployeeId = 3,
                            Adress = "580 Ollie Mount, Trompton, Comoros",
                            DepartmentId = 4,
                            Email = "Chelsea6@gmail.com",
                            FirstName = "Kayden",
                            Gender = "Female",
                            LastName = "Feest",
                            PhoneNumber = "607.976.3843 x50701",
                            Salary = 6489.6400000000003
                        },
                        new
                        {
                            EmployeeId = 4,
                            Adress = "611 Sauer Estates, New Greggfurt, Austria",
                            DepartmentId = 3,
                            Email = "Haylee71@hotmail.com",
                            FirstName = "Rudy",
                            Gender = "Female",
                            LastName = "Ernser",
                            PhoneNumber = "983.739.9362",
                            Salary = 8122.6700000000001
                        },
                        new
                        {
                            EmployeeId = 5,
                            Adress = "4996 Kutch Squares, Pfeffermouth, Mali",
                            DepartmentId = 2,
                            Email = "Howell40@gmail.com",
                            FirstName = "Jennyfer",
                            Gender = "Male",
                            LastName = "Turner",
                            PhoneNumber = "395-557-1271 x08593",
                            Salary = 2791.1199999999999
                        },
                        new
                        {
                            EmployeeId = 6,
                            Adress = "30496 Emiliano Stream, North Karliemouth, Kenya",
                            DepartmentId = 4,
                            Email = "Anderson.Spinka@hotmail.com",
                            FirstName = "Hermina",
                            Gender = "Male",
                            LastName = "Donnelly",
                            PhoneNumber = "986-997-0308",
                            Salary = 791.20000000000005
                        },
                        new
                        {
                            EmployeeId = 7,
                            Adress = "8737 Deangelo Path, Ladariusville, Palestinian Territory",
                            DepartmentId = 4,
                            Email = "Dortha.Hahn@hotmail.com",
                            FirstName = "Alexander",
                            Gender = "Male",
                            LastName = "Robel",
                            PhoneNumber = "447.800.7207 x47209",
                            Salary = 5049.6800000000003
                        },
                        new
                        {
                            EmployeeId = 8,
                            Adress = "5001 Marlen Causeway, Schroedershire, Western Sahara",
                            DepartmentId = 3,
                            Email = "Raoul13@gmail.com",
                            FirstName = "Sophie",
                            Gender = "Female",
                            LastName = "Wiegand",
                            PhoneNumber = "873-977-8918 x44357",
                            Salary = 6790.6700000000001
                        },
                        new
                        {
                            EmployeeId = 9,
                            Adress = "8269 Harris Viaduct, Danielview, Palestinian Territory",
                            DepartmentId = 5,
                            Email = "Ashly.Beier90@hotmail.com",
                            FirstName = "Wilfredo",
                            Gender = "Male",
                            LastName = "Thiel",
                            PhoneNumber = "248-270-0865",
                            Salary = 391.50999999999999
                        },
                        new
                        {
                            EmployeeId = 10,
                            Adress = "624 Cole Ways, Dylanberg, Venezuela",
                            DepartmentId = 4,
                            Email = "Conner70@gmail.com",
                            FirstName = "Javier",
                            Gender = "Female",
                            LastName = "Powlowski",
                            PhoneNumber = "1-455-245-7506",
                            Salary = 3529.0500000000002
                        },
                        new
                        {
                            EmployeeId = 11,
                            Adress = "49597 Hyatt Way, West Trevion, Austria",
                            DepartmentId = 2,
                            Email = "Shad.Homenick21@hotmail.com",
                            FirstName = "Taurean",
                            Gender = "Male",
                            LastName = "Wisoky",
                            PhoneNumber = "1-565-573-4052",
                            Salary = 4911.1099999999997
                        },
                        new
                        {
                            EmployeeId = 12,
                            Adress = "71772 Rahul Mount, Maidafurt, British Indian Ocean Territory (Chagos Archipelago)",
                            DepartmentId = 3,
                            Email = "Ernesto43@gmail.com",
                            FirstName = "Prudence",
                            Gender = "Female",
                            LastName = "Lakin",
                            PhoneNumber = "719.645.3968",
                            Salary = 1058.7
                        },
                        new
                        {
                            EmployeeId = 13,
                            Adress = "87241 Mraz Viaduct, Strosintown, United States Minor Outlying Islands",
                            DepartmentId = 2,
                            Email = "Kiel5@gmail.com",
                            FirstName = "Zachery",
                            Gender = "Female",
                            LastName = "Zulauf",
                            PhoneNumber = "(885) 839-2040",
                            Salary = 327.91000000000003
                        },
                        new
                        {
                            EmployeeId = 14,
                            Adress = "533 Selina Vista, Port Annalise, Nigeria",
                            DepartmentId = 4,
                            Email = "Alexandrea61@yahoo.com",
                            FirstName = "Liam",
                            Gender = "Male",
                            LastName = "Brekke",
                            PhoneNumber = "817-824-4723 x4744",
                            Salary = 7917.5100000000002
                        },
                        new
                        {
                            EmployeeId = 15,
                            Adress = "350 MacGyver Divide, South Maeland, Syrian Arab Republic",
                            DepartmentId = 5,
                            Email = "Otilia.King@yahoo.com",
                            FirstName = "Steve",
                            Gender = "Male",
                            LastName = "Wilkinson",
                            PhoneNumber = "1-617-453-5934",
                            Salary = 8841.6299999999992
                        },
                        new
                        {
                            EmployeeId = 16,
                            Adress = "710 Herman Dam, Lindberg, Libyan Arab Jamahiriya",
                            DepartmentId = 5,
                            Email = "Flavie.Cole@yahoo.com",
                            FirstName = "Noel",
                            Gender = "Female",
                            LastName = "Torphy",
                            PhoneNumber = "404.864.2781 x1927",
                            Salary = 4498.9700000000003
                        },
                        new
                        {
                            EmployeeId = 17,
                            Adress = "28529 Christopher Valleys, South Myles, Mauritius",
                            DepartmentId = 5,
                            Email = "Ebba.Altenwerth@yahoo.com",
                            FirstName = "Jadyn",
                            Gender = "Female",
                            LastName = "Runolfsdottir",
                            PhoneNumber = "935.662.6618 x90308",
                            Salary = 2502.5500000000002
                        },
                        new
                        {
                            EmployeeId = 18,
                            Adress = "79275 Cecil Ports, Port Chet, Romania",
                            DepartmentId = 2,
                            Email = "Ashton_Frami@hotmail.com",
                            FirstName = "Makenzie",
                            Gender = "Female",
                            LastName = "Mayert",
                            PhoneNumber = "588.385.8041 x96634",
                            Salary = 4140.2399999999998
                        },
                        new
                        {
                            EmployeeId = 19,
                            Adress = "43690 Kamren Square, Enochside, Faroe Islands",
                            DepartmentId = 5,
                            Email = "Lauryn.Greenfelder@yahoo.com",
                            FirstName = "Kiara",
                            Gender = "Male",
                            LastName = "O'Keefe",
                            PhoneNumber = "642-360-2659",
                            Salary = 8846.2199999999993
                        },
                        new
                        {
                            EmployeeId = 20,
                            Adress = "81744 Graham Station, Walterborough, Canada",
                            DepartmentId = 1,
                            Email = "Garrick_Nolan87@gmail.com",
                            FirstName = "Nikko",
                            Gender = "Male",
                            LastName = "Leuschke",
                            PhoneNumber = "(368) 501-4994 x862",
                            Salary = 5296.6700000000001
                        });
                });

            modelBuilder.Entity("Labb2_Avancerad.Models.Employee", b =>
                {
                    b.HasOne("Labb2_Avancerad.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });
#pragma warning restore 612, 618
        }
    }
}
